config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'

  root 'landing#index'

  resources :outlines, only: %w(index show new edit update) do
    post :add_element
    post :remove_element
    post :clone
    post :create_tool_and_element
    post :add_tool_element
    collection do
      get :search
    end
    resources :elements, only: %w(destroy)
  end

  resources :tools, only: %w() do
    collection do
      get :search
    end
  end

  resources :courses, only: %w() do
    get :autocomplete_course_code, on: :collection
  end

  resources :job_messages, only: %w(show), param: :job_id

end

app/models/outline.rb
class Outline < ActiveRecord::Base

  before_save :set_type
  before_destroy :destroy_elements
  belongs_to :user
  belongs_to :course
  belongs_to :parent, class_name: 'Template'
  # has_many :outline_elements, -> { order(order: :asc )}, dependent: :destroy
  # has_many :elements, through: :outline_elements
  has_many :element_groups, -> { order(rank: :asc)}, dependent: :destroy
  has_many :elements, through: :element_groups
  has_many :senate_rules, through: :elements

  default_scope { where(type: 'Outline') }
  #accepts_nested_attributes_for :outline_elements, allow_destroy: true
  accepts_nested_attributes_for :element_groups, allow_destroy: true

  scope :sorted_by, -> (sort_option) {
                    # extract the sort direction from the param value.
                    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
                    case sort_option.to_s
                      when /^created_at_/
                        order("outlines.created_at #{ direction }")
                      when /^code_/
                        joins(:course).order("courses.code #{direction}")
                      else
                        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
                    end
                  }



  scope :search_query, ->(code) {
    courses = Course.arel_table
    return Outline.none if code.blank?
    joins(:course).where(courses[:code].matches("%#{code}%"))
  }

  scope :recent_outlines, ->(num_outlines) {
    order(created_at: :desc).limit(num_outlines)
  }

  scope :outlines_only, -> {
    where(type: 'Outline')
  }

  filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [ :search_query, :sorted_by ]
  )
  def self.options_for_sorted_by
    [
        ['Course Code (a-z)', 'code_asc'],
        ['Creation date (newest first)', 'created_at_desc'],
        ['Creation date (oldest first)', 'created_at_asc'],
    ]
  end

  def code
    course.code
  end

  def set_type
    self.type = 'Outline'
  end

  def add_element(order, element_type = 'text')
    #TODO: Support for other element types
    element = Element.new
    outline_elements << OutlineElement.new(outline_id: id, element: element)
    save!
    element
  end

  def add_existing_element(element_id, element_rank, group_rank)
    element = Element.find(element_id).clone
    group = nil
    if group_rank.blank?
      group = ElementGroup.create(rank: element_rank, outline: Outline.find(id))
    else
      group = ElementGroup.where(outline_id: id, rank: group_rank).first
      element.rank = element_rank
    end
    group.elements << element
    element
  end

  def destroy_elements
    elements.each do |ele|
      ele.destroy if ele.outline_elements.size <= 1
    end
  end

  def add_tool_and_element(header, outline_content, tool_name )
    header = Header.new if header.nil?
    element = Element.create(text: outline_content, rank: -1)
    element.create_header(text: header[:text],
                          size: header[:size],
                          bold: header[:bold],
                          italic: header[:italic],
                          underline: header[:underline]
    )

    Tool.insert(tool_name, element.id, parent.category.faculty.id)
  end

end

app/controllers/outlines_controller.rb
class OutlinesController < ApplicationController
  load_and_authorize_resource

  def index
    @filterrific = initialize_filterrific(
        Outline,
        params[:filterrific],
        select_options: {
            sorted_by: Outline.options_for_sorted_by
        }
    ) or return
    @outlines = @filterrific.find.page(params[:page])

    @current_outlines = Outline.recent_outlines(2);
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def show

  end

  def new
    @template = @outline.parent
    @course_code = params[:course][:course_code]
  end

  def clone
    @current_job = CloneTemplate.perform_later(user_id: current_user.id,
                                               course_code: params[:course_code],
                                               parent_id: params[:outline_id],
                                               senate_rules: senate_rules)
  end

  def edit
    @outline_tools = Tool.list_query(@outline.parent.faculty.id)
  end

  def search
    @query = params[:search][:query] if params[:search]
    @outlines = Outline.search_query(@query)
  end

  def update
    @outline.update_attributes(outline_params)
    respond_to do |format|
      format.html { redirect_to edit_outline_path }
      format.js {}
    end
  end

  def add_element
    #TODO: Add order to the element
    @outline = Outline.where(id: params[:outline_id]).first
    @element = @outline.add_element(5) #Change this
  end

  def add_tool_element
    @outline = Outline.find(params[:outline_id])
    @outline.add_existing_element(params[:outline][:element][:element_id],
                                  params[:outline][:element][:rank],
                                  params[:outline][:element_group][:rank])

    redirect_to action: 'edit', id: params[:outline_id]
  end

  def remove_element
    outline_element = OutlineElement.where(id: params[:outline_element_id].to_i).first
    outline_element.destroy
    @outline_element_id = params[:outline_element_id]
  end

  # adds new tool and corresponding element that it creates
  def create_tool_and_element
    if params[:outline][:element][:text].blank? || params[:outline][:tool][:name].blank?
      redirect_to :back
      return
      # TODO: Have a detailed error message returned. UI validation would be nice as well
    end
    @outline = Outline.find(params[:outline_id])
    @outline.add_tool_and_element(params[:outline][:element][:header],
                                  params[:outline][:element][:text],
                                  params[:outline][:tool][:name])
    redirect_to :back
  end

  private

  def outline_params
    params.require(:outline).permit(:course_id, :parent_id, header_attributes:[:text, :bold, :italic, :underline, :size], element_groups_attributes:[:id, :rank, elements_attributes:[:id, :text, :rank, header_attributes:[:text, :bold, :italic, :underline, :size]]])
  end
  def senate_rules
    params.require(:senate_rules)
  end
end

app/helpers/outlines_helper.rb
module OutlinesHelper

  def get_senate_rules(template)
    faculty = template.faculty
    faculty.senate_rules
  end

  def header_class(header)
    klass = ''
    klass += 'bold ' if header.bold
    klass += 'italic ' if header.italic
    klass += 'underline ' if header.underline
    klass += "font-#{header.size}" if header.size
    klass
  end

end

app/views/outlines/clone.html.erb
<div id="window-content">

</div>

<script type="application/javascript">
  $(function() {
    $('#alert-div').html("<div class='alert alert-info'> Processing <span class='fa fa-spinner fa-spin'></span> </div> ");
    return $.poll(function(retry) {
      return $.getJSON("<%= job_message_path(@current_job.job_id) %>", function(data) {
        if (data) {
          if (data.status === "succeeded") {
            $('#alert-div').html("<div class='alert alert-success'> Finished Processing. Reloading...  </div> ");
            return setTimeout((function() {
              window.location.replace("<%= root_url %>".slice(0, -1) + data.message)
            }), 1500);
          } else if (data.status === "failed") {
            return $('#alert-div').html("<div class='alert alert-danger'> Processing failed: " + data.message + "</div>");
          } else {
            return retry();
          }
        } else {
          return retry();
        }
      });
    });
  });
</script>

app/views/outlines/create.html.erb
<div id="window-content">

</div>

<script type="application/javascript">
  $(function() {
    $('#alert-div').html("<div class='alert alert-info'> Processing <span class='fa fa-spinner fa-spin'></span> </div> ");
    return $.poll(function(retry) {
      return $.getJSON("<%= job_message_path(@current_job.job_id) %>", function(data) {
        if (data) {
          if (data.status === "succeeded") {
            $('#alert-div').html("<div class='alert alert-success'> Finished Processing. Reloading...  </div> ");
            return setTimeout((function() {
              window.location.replace("<%= root_url %>".slice(0, -1) + data.message)
            }), 1500);
          } else if (data.status === "failed") {
            return $('#alert-div').html("<div class='alert alert-danger'> Processing failed: " + data.message + "</div>");
          } else {
            return retry();
          }
        } else {
          return retry();
        }
      });
    });
  });
</script>

app/views/outlines/edit.html.erb
Course Code: <%= @outline.course.code %>
<div id="edit_outlines" class="container-fluid outline-editor">
  <tr>
    <%= render 'outlines/partials/edit_toolbar', outline: @outline %>
      <%= render 'outlines/partials/edit_elements', outline: @outline, outline_tools: @outline_tools %>
  </tr>
</div>


<%#= javascript_include_tag 'outlines', 'data-turbolinks-track' => true %>

<!--<div class="container-fluid outline-edit-container">-->
  <!--<div id="outside-form">-->
    <!--&lt;!&ndash; we may need to throw all content that doesn't belong to the outline object here on submit &ndash;&gt;-->
    <!--&lt;!&ndash; issue is we need the form page to respond to elements being dragged onto it &ndash;&gt;-->
  <!--</div>-->
  <!--<h2 class="outline-edit-title"> Outline Editor - <%= @outline.course.code %> </h2>-->
  <!--<%#= render 'outlines/partials/draggable_edit_element', outline: @outline  %>-->
<!--</div>-->

app/views/outlines/index.coffee.erb
console.log 'wheee'   

app/views/outlines/index.html.erb
<div class="container-fluid">
  <h2> Latest Outlines: </h2>
  <div id="latest-div">
    <% @current_outlines.in_groups_of(12, false) do |outlines| %>
      <div class="row">
        <% outlines.each do |outline| %>
          <div class="col-md-1">
            <button class="btn btn-default top-outline"><%= outline.course.code %></button>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <h2> Filter Outlines: </h2>
  <div id="filter-div">
    <%= form_for_filterrific @filterrific do |f| %>
      <div class="form-group">
        <%= f.text_field :search_query, class: 'filterrific-periodically-observed', id: 'filter-search' %>
        <%= f.select :sorted_by, @filterrific.select_options[:sorted_by], {}, id: 'filter-select' %>
        <%= f.submit 'Apply Filters', class: 'btn btn-western btn-sm', id: 'filter-submit' %>
      </div>
    <% end %>
    <% @outlines.each do |out| %>
      <%= out.course.code %>
    <% end %>
  </div>
</div>

app/views/outlines/new.html.erb
<div class="container-fulid">
  <%= form_for :senate_rules, url: outline_clone_path(outline_id: @template.id, course_code: @course_code) do |f| %>
    <div class="senate-rules">
      <% get_senate_rules(@template).each_with_index do |rule, idx| %>
        <div class="row senate-rule <%= idx % 2 == 0 ? 'pure-white-bg' : ''  %>">
          <div class="col-md-10 rule-col">
            <%= f.label rule.id, rule.description %>
          </div>
          <div class="col-md-2">
            <%= f.check_box rule.id, class: 'toggle-check', data: {'on-text': 'Yes', 'off-text': 'No', 'on-color': 'success'} %>
          </div>
        </div>
      <% end %>
      <div class="pull-right">
        <br>
        <%= f.submit 'Continue', class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/outlines/search.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <%= form_for :search, url: search_outlines_path, method: :get, html: { class: 'form-inline' } do |f| %>
        <%= f.text_field :query, class: 'form-control', value: @query, id: 'search-page-search' %>
        <%= f.submit 'Search Outlines', class: 'btn btn-default', id: 'search-page-submit' %>
      <% end %>
    </div>
  </div>
  <% if @outlines.empty? && @query.present? %> No results found for <strong><%= @query %></strong>. <% end %>
  <% @outlines.each do |outline| %>
    <%= outline.course.code %>
  <% end %>
</div>

app/views/outlines/show.html.erb
Course Code: <%= @outline.course.code %> </br>
<% @outline.elements.each do |element| %>
  <%= element.text.html_safe %>
<% end %>