config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'

  root 'landing#index'

  resources :outlines, only: %w(index show new edit update) do
    post :add_element
    post :remove_element
    post :clone
    post :create_tool_and_element
    post :add_tool_element
    collection do
      get :search
    end
    resources :elements, only: %w(destroy)
  end

  resources :tools, only: %w() do
    collection do
      get :search
    end
  end

  resources :courses, only: %w() do
    get :autocomplete_course_code, on: :collection
  end

  resources :job_messages, only: %w(show), param: :job_id

end

app/models/outline.rb
class Outline < ActiveRecord::Base

  before_save :set_type
  before_destroy :destroy_elements
  belongs_to :user
  belongs_to :course
  belongs_to :parent, class_name: 'Template'
  # has_many :outline_elements, -> { order(order: :asc )}, dependent: :destroy
  # has_many :elements, through: :outline_elements
  has_many :element_groups, -> { order(rank: :asc)}, dependent: :destroy
  has_many :elements, through: :element_groups
  has_many :senate_rules, through: :elements

  default_scope { where(type: 'Outline') }
  #accepts_nested_attributes_for :outline_elements, allow_destroy: true
  accepts_nested_attributes_for :element_groups, allow_destroy: true

  scope :sorted_by, -> (sort_option) {
                    # extract the sort direction from the param value.
                    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
                    case sort_option.to_s
                      when /^created_at_/
                        order("outlines.created_at #{ direction }")
                      when /^code_/
                        joins(:course).order("courses.code #{direction}")
                      else
                        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
                    end
                  }



  scope :search_query, ->(code) {
    courses = Course.arel_table
    return Outline.none if code.blank?
    joins(:course).where(courses[:code].matches("%#{code}%"))
  }

  scope :recent_outlines, ->(num_outlines) {
    order(created_at: :desc).limit(num_outlines)
  }

  scope :outlines_only, -> {
    where(type: 'Outline')
  }

  filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [ :search_query, :sorted_by ]
  )
  def self.options_for_sorted_by
    [
        ['Course Code (a-z)', 'code_asc'],
        ['Creation date (newest first)', 'created_at_desc'],
        ['Creation date (oldest first)', 'created_at_asc'],
    ]
  end

  def code
    course.code
  end

  def set_type
    self.type = 'Outline'
  end

  def add_element(order, element_type = 'text')
    #TODO: Support for other element types
    element = Element.new
    outline_elements << OutlineElement.new(outline_id: id, element: element)
    save!
    element
  end

  def add_existing_element(element_id, element_rank, group_rank)
    element = Element.find(element_id).clone
    group = nil
    if group_rank.blank?
      group = ElementGroup.create(rank: element_rank, outline: Outline.find(id))
    else
      group = ElementGroup.where(outline_id: id, rank: group_rank).first
      element.rank = element_rank
    end
    group.elements << element
    element
  end

  def destroy_elements
    elements.each do |ele|
      ele.destroy if ele.outline_elements.size <= 1
    end
  end

  def add_tool_and_element(header, outline_content, tool_name )
    header = Header.new if header.nil?
    element = Element.create(text: outline_content, rank: -1)
    element.create_header(text: header[:text],
                          size: header[:size],
                          bold: header[:bold],
                          italic: header[:italic],
                          underline: header[:underline]
    )

    Tool.insert(tool_name, element.id, parent.category.faculty.id)
  end

end

app/controllers/outlines_controller.rb
class OutlinesController < ApplicationController
  load_and_authorize_resource

  def index
    @filterrific = initialize_filterrific(
        Outline,
        params[:filterrific],
        select_options: {
            sorted_by: Outline.options_for_sorted_by
        }
    ) or return
    @outlines = @filterrific.find.page(params[:page])

    @current_outlines = Outline.recent_outlines(2);
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def show

  end

  def new
    @template = @outline.parent
    @course_code = params[:course][:course_code]
  end

  def clone
    @current_job = CloneTemplate.perform_later(user_id: current_user.id,
                                               course_code: params[:course_code],
                                               parent_id: params[:outline_id],
                                               senate_rules: senate_rules)
  end

  def edit
    @outline_tools = Tool.list_query(@outline.parent.faculty.id)
  end

  def search
    @query = params[:search][:query] if params[:search]
    @outlines = Outline.search_query(@query)
  end

  def update
    @outline.update_attributes(outline_params)
    respond_to do |format|
      format.html { redirect_to edit_outline_path }
      format.js {}
    end
  end

  def add_element
    #TODO: Add order to the element
    @outline = Outline.where(id: params[:outline_id]).first
    @element = @outline.add_element(5) #Change this
  end

  def add_tool_element
    @outline = Outline.find(params[:outline_id])
    @outline.add_existing_element(params[:outline][:element][:element_id],
                                  params[:outline][:element][:rank],
                                  params[:outline][:element_group][:rank])

    redirect_to action: 'edit', id: params[:outline_id]
  end

  def remove_element
    outline_element = OutlineElement.where(id: params[:outline_element_id].to_i).first
    outline_element.destroy
    @outline_element_id = params[:outline_element_id]
  end

  # adds new tool and corresponding element that it creates
  def create_tool_and_element
    if params[:outline][:element][:text].blank? || params[:outline][:tool][:name].blank?
      redirect_to :back
      return
      # TODO: Have a detailed error message returned. UI validation would be nice as well
    end
    @outline = Outline.find(params[:outline_id])
    @outline.add_tool_and_element(params[:outline][:element][:header],
                                  params[:outline][:element][:text],
                                  params[:outline][:tool][:name])
    redirect_to :back
  end

  private

  def outline_params
    params.require(:outline).permit(:course_id, :parent_id, header_attributes:[:text, :bold, :italic, :underline, :size], element_groups_attributes:[:id, :rank, elements_attributes:[:id, :text, :rank, header_attributes:[:text, :bold, :italic, :underline, :size]]])
  end
  def senate_rules
    params.require(:senate_rules)
  end
end

app/helpers/outlines_helper.rb
module OutlinesHelper

  def get_senate_rules(template)
    faculty = template.faculty
    faculty.senate_rules
  end

  def header_class(header)
    klass = ''
    klass += 'bold ' if header.bold
    klass += 'italic ' if header.italic
    klass += 'underline ' if header.underline
    klass += "font-#{header.size}" if header.size
    klass
  end

end

app/views/outlines/partials/_draggable_edit_element.html.erb
<%= form_for outline, url: outline_path(outline), method: :put do |f| %>
  <div class="row outline-editor">
    <div class="col-md-1">
      <div class="btn-group-vertical outline-toolbar">

        <!-- This is where we will populate toolbar content
        <%# @toolbar_elements.each do |out| %>
        <div id="create-paragraph" class="tool draggable">
          <label>
             *Toolbar item title*
             We'll want some field to say if it is cloneable or not
          </label>
        </div>
        <%# end %> -->
        <!-- this tooldbar element demonstrates passing html content to jquery via hidden input -->
        <div class="tool draggable cloneable">
          <label> Cloneable Element </label>
          <input id="element-html-content" hidden="true" value="<div class='tool draggable'><h3>Heading</h3><p>New content element from rails!</p></div>"/><!-- <%# item.htmlContent %> -->
        </div>
        <div class="tool draggable"> Test
          <input id="element-order"/>
        </div>
        <div class="tool draggable"> Test 2
          <input id="element-order"/>
        </div>
        <div class="tool draggable"> Test 3
          <input id="element-order"/>
        </div>
      </div>
    </div>
    <!-- this is the actual form that the user is creating, elements will be dragged into here -->
    <div class="col-md-11 outline-view sortable">
      <!-- getting rails to recognize elements dragged into here in the js may be tricky.. -->
      <%= f.fields_for :outline_elements do |f_oe| %>
        <div class="element-edit" id="element-edit-<%= f_oe.object.id %>">
          <%= f_oe.fields_for :element do |f_e| %>
            <% unless f_e.object.required? %>
              <%= link_to outline_remove_element_path(outline_id: outline.id, outline_element_id: f_oe.object.id), class: 'close', method: :post, remote: true do %>&times<% end %>
            <% end %>
            <div class="element-text sortable draggable">
              <% obj = f_e.object %>
              <% if obj.unmutable? %>
                <%= obj.text.html_safe %>
              <% else %>
                <%= f_e.text_area :text, class: 'ckeditor' %>
              <% end %>
            </div>
          <% end %>
          <%= f_oe.hidden_field :order, value: f_oe.object.order %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/outlines/partials/_edit_element.html.erb
<div class=" outline-view">
<%= form_for outline, url: outline_path(outline), method: :put, remote: true do |f| %>
    <td>
  <div class="sortable">
    <%= f.fields_for :outline_elements do |f_oe| %>
      <div class="element-edit" id="element-edit-<%= f_oe.object.id %>">
        <%= f_oe.fields_for :element do |f_e| %>
          <div class="element-text">
            <% unless f_e.object.required? %>
              <%= link_to outline_remove_element_path(outline_id: outline.id, outline_element_id: f_oe.object.id), class: 'close', method: :post, remote: true do %>&times<% end %>
            <% end %>
            <% obj = f_e.object %>
            <div class="html-element">
              <div class="html-element-text">
                <%= obj.text.try(:html_safe) %>
              </div>
              <% unless obj.immutable? %> <a href="#" class="display-editor"><span>...Click to edit</span></a> <% end %>
            </div>
            <% if obj.immutable? %>
            <% else %>
              <div class="ckeditor-element hidden">
                <%= f_e.text_area :text, class: 'ckeditor' %>
                <a href="#" class="hide-editor"><span>...Click to hide</span></a>
              </div>
            <% end %>
          </div>

        <% end %>
        <%= f_oe.hidden_field :order, value: f_oe.object.order, class: 'element-order' %>
        <%# This is where rank stuff will go so put it here %>
      </div>
    <% end %>
  </div>
  <%= f.submit class: 'btn btn-western' %>
<% end %>
<td>
<%= button_to 'Add Element', outline_add_element_path(@outline), class: 'btn btn-western btn-sm', remote: true %>
</div>

app/views/outlines/partials/_edit_elements.html.erb
<div id="edit_outline_elements" class="outline-view">
  <%= form_for outline, url: outline_path(outline), method: :put, remote: true do |f| %>
    <div class="element-group-list">
      <%= f.fields_for :element_groups do |f_eg| %>
        <div class="element-group list">
          <% if f_eg.object.header %>
            <div class="element-group-header <%= header_class(f_eg.object.header) %>">
              <%= f_eg.object.header.text %>
            </div>
          <% end %>
          <div class="elements">
            <%= f_eg.fields_for :elements do |f_e| %>
              <div class="element-text list" id="element_<%= f_e.object.id %>">
              <%= f_e.fields_for :header do |f_h| %>
                <div class="row">
                  <div class="html-element-header col-md-7">
                    <%= f_h.text_field :text, class: "header-edit #{header_class(f_e.object.header)}" %>
                  </div>
                  <div class="col-md-5">
                    <%= f_h.label :bold do %> <span class="bold">bold</span> <% end %>
                    <%= f_h.check_box :bold, class: 'format-checkbox', 'data-style': 'bold' %>
                    <%= f_h.label :italic do %> <span class="italic">italic</span> <% end %>
                    <%= f_h.check_box :italic, class: 'format-checkbox', 'data-style': 'italic' %>
                    <%= f_h.label :underline do %> <span class="underline">underline</span> <% end %>
                    <%= f_h.check_box :underline, class: 'format-checkbox', 'data-style': 'underline' %>
                    <%= f_h.select :size, options_for_select(Header.select_options, f_h.object.size), {}, {class: 'format-size'} %>
                  </div>
                </div>
              <% end %>
                <%= render 'elements/text_element', object: f_e.object, f_e: f_e, outline: outline %>
                <% unless f_e.object.required? %>
                  <%= link_to outline_element_path(outline_id: outline.id, id: f_e.object.id),
                              class: 'close',
                              method: :delete,
                              remote: true,
                              'data-confirm': 'Do you really want to remove this element?' do %>
                    remove
                  <% end %>
                <% end %>
                <%= f_e.hidden_field :rank, class: 'list-rank' %>
              </div>
            <% end %>
            &nbsp
          </div>
          <%= f_eg.hidden_field :rank, class: 'list-rank' %>
        </div>
      <% end %>
    </div>
      <%= f.submit %>
  <% end %>
</div>

app/views/outlines/partials/_edit_toolbar.html.erb
<div class="btn-group-vertical outline-toolbar">
  <span id="tool-add" class="glyphicon glyphicon-plus tool-add" data-toggle="modal" data-target="#tool-modal"></span>

        <% @outline_tools.each do |o_t| %>

        <div class="tool draggable cloneable">
          <label> <%= o_t.name %> </label>
          <!-- have the content be previewed on drag. The header won't be 100% accurate -->
          <input class="element-html-content" hidden="true" value="<div id='new_element' class='element-text list'>
          <h3> <%= o_t.element.header.text %> </h3>
          <%= o_t.element.text %>
           <input class='list-rank' hidden='true'>
           <input class='element-id' hidden='true' value=<%= o_t.element.id %> >
          </div>">
        </div>
        <% end %>
  <div id="add_tool_element">
  <%= form_for outline, url: outline_add_tool_element_path(@outline), method: :post do |f| %>
      <%= f.fields_for :element do |f_e| %>
            <%= f_e.hidden_field :element_id, class: 'element-id' %>
            <%= f_e.hidden_field :rank, class: 'list-rank' %>
      <%end%>
        <%= f.fields_for :element_group do |f_eg| %>
            <%= f_eg.hidden_field :rank, class: 'group-rank' %>
            <% end %>
        <%= f.submit hidden: true %>
  <% end %>
  </div>
  <%= render 'outlines/partials/edit_toolbar_create', outline: @outline %>
</div>

app/views/outlines/partials/_edit_toolbar_create.erb
<div id="tool-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for outline, url: outline_create_tool_and_element_path(@outline), method: :post do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3 class="modal-title">Add Toolbar Element</h3>
          </div>
          <div class="modal-body">
            <%= f.fields_for :tool do |f_t| %>
                <h4> Tool Title: </h4>
                <div>
                  <%= f_t.text_field :name %>
                </div>
            <% end %>

            <%= f.fields_for :element do |f_e| %>
                <%= f_e.fields_for :header do |f_h| %>
                    <h4> Element Header: (optional) </h4>
                    <div>
                      <div class="toolbar-header-options" >
                        <%= f_h.text_field :text, class: 'header-edit' %>
                      </div>
                      <div class="toolbar-header-options" >
                        <%= f_h.label :bold %>
                        <%= f_h.check_box :bold %>
                        <%= f_h.label :italic %>
                        <%= f_h.check_box :italic %>
                        <%= f_h.label :underline %>
                        <%= f_h.check_box :underline %>
                        <%= f_h.select :size, options_for_select(Header.select_options, Header.select_options[1]) %>
                      </div>
                    </div>
                <% end %>

                <h4> Element Content: </h4>
                <div class="element-text">
                  <div class="html-element">
                    <div class="html-element-text">
                    </div>
                    <a href="#" class="display-editor"><span>Click to edit</span></a>
                  </div>
                  <div class="ckeditor-element hidden">
                    <%= f_e.text_area :text, class: 'ckeditor' %>
                    <a href="#" class="hide-editor"><span>Click to hide</span></a>
                  </div>
                </div>
            <%end%>
          </div>

          <div class="modal-footer">
            <%= f.submit 'Add Tool', class: 'btn btn-western' %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
      <%end%>

    </div>
  </div>
</div>

app/views/outlines/partials/_outlines_create_view.html.erb
Outlines Create View

app/views/outlines/partials/_templates_create_view.html.erb
Template Create