config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'

  root 'landing#index'

  resources :outlines, only: %w(index show new edit update) do
    post :add_element
    post :remove_element
    post :clone
    post :create_tool_and_element
    post :add_tool_element
    collection do
      get :search
    end
    resources :elements, only: %w(destroy)
  end

  resources :tools, only: %w() do
    collection do
      get :search
    end
  end

  resources :courses, only: %w() do
    get :autocomplete_course_code, on: :collection
  end

  resources :job_messages, only: %w(show), param: :job_id

end

app/views/shared/_login_form.html.erb
<div class="container-fluid">
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="field">
      <%= f.label :email, 'E-Mail Address' %>
      <%= f.email_field :email, autofocus: true, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: 'off', class: 'form-control' %>
    </div>
    <br>
    <div class="row">
      <div class="col-md-8">
        <% if devise_mapping.rememberable? -%>
          <div class="field">
            <%= f.label :remember_me, '', class: 'checkbox-inline' do %>
              <%= f.check_box :remember_me %> <span class="checkbox-label"> Remember me </span>
            <% end %>
          </div>
        <% end -%>
        <%= link_to 'Forgot your password?', new_password_path(resource_name) %>
      </div>
      <div class="col-md-4" id="login-button-div">
        <%= f.button 'Log in', class: 'btn btn-success pull-right', id: 'login-button' %>
      </div>
    </div>

  <% end %>
</div>

app/views/shared/_new_outline_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-western btn-lg" data-toggle="modal" data-target="#outlineCreateModal">
  Create New Outline
</button>

<!-- Modal -->
<div class="modal fade" id="outlineCreateModal" tabindex="-1" role="dialog" aria-labelledby="outlineCreateModalLabel">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Create New Outline</h4>
        </div>
      <div class="modal-body">
        <%= form_for Outline.new, url: new_outline_path, method: :get, html: { class: 'form-inline' } do |f| %>
          <div class="form-group">
            <%= fields_for :course do |ff| %>
              <%= ff.label :course_code %>
              <%= ff.autocomplete_field :course_code, autocomplete_course_code_courses_path, class: 'form-control course-code-picker', data: { 'autocomplete-label': '' } %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :parent_id, 'Template' %>
            <%= f.select :parent_id,
                         templates.map { |c| [c.department_name, c.id]},
                         { include_blank: true},
                         { class: 'chosen-select' }
            %>
          </div>
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit class: ' btn btn-primary' %>
        </div>
    <% end %>
    </div>
  </div>
</div>