config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'

  root 'landing#index'

  resources :outlines, only: %w(index show new edit update) do
    post :add_element
    post :remove_element
    post :clone
    post :create_tool_and_element
    post :add_tool_element
    collection do
      get :search
    end
    resources :elements, only: %w(destroy)
  end

  resources :tools, only: %w() do
    collection do
      get :search
    end
  end

  resources :courses, only: %w() do
    get :autocomplete_course_code, on: :collection
  end

  resources :job_messages, only: %w(show), param: :job_id

end

app/views/layouts/_alert.html.erb
<div class="container-fluid">
  <div class="row", id="alert-div">
    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer western-purple-bg hidden">
  <span class="white"> Here is some footer stuff</span>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default western-purple-bg western-purple-border">
  <div >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="http://www.uwo.ca">
        <%= image_tag 'western_logo.gif', id: 'western-logo' %>
      </a>
      <br>
      <a href="<%= root_path %>">
        <%=image_tag('logo.jpg', height: '53', width: '300', class: 'logo')%>
      </a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if can? :create, Outline %>
          <li><a href="#" class="white"> Create Outline </a></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Navigation <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View Outlines', outlines_path %></li>
            <% if can? :create, Outline %>
              <li><a href="#">Create Outline</a
              ></li>
            <% end %>

            <li><a href="#">Option 3</a></li>
          </ul>
        </li>
        <% if current_user.guest? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="login-link">Login</a>
            <ul class="dropdown-menu" id="login-menu">
              <%= render 'shared/login_form' %>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'white pull-right', id: 'log-out-link' do %>
              <span class="fa fa-user"></span>&nbsp<%= current_user.name %><br><br>
              <span>Log Out</span>
            <% end %>
          </li>
        <% end %>
      </ul>
      <%= form_for :search, url: search_outlines_path, method: :get, html: { class: 'navbar-form navbar-right' } do |f| %>
        <br><br>
        <%= f.text_field :query, class: 'form-control', id: 'nav-search' %>
        <%= f.submit 'Search Outlines', class: 'btn btn-default', id: 'nav-submit' %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Syllabus Creator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="body">
    <%= render 'layouts/nav' %>
    <%= render 'layouts/alert' %>
    <%= yield %>
    <div class="clearfix"></div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>